version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Installer les dépendances
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install flake8 pytest
      - run:
          name: Vérifier la qualité du code
          command: |
            . venv/bin/activate
            flake8 .
      - run:
          name: Lancer les tests unitaires
          command: |
            . venv/bin/activate
            pytest
